print("Name: James Dominic P. Tion")
print("Course: B.S. Computer Science")
print("Section: CS1D")
print("Age: 21")
print("Birthday: August 27,2002")
print("Address: blk 52 lot 10 phase 1 nha kauswagan")
print(" ")
print("Name: Ashley Jan G. Buar")
print("Course: B.S Computer Science")
print("Section: CS1D")
print("Age: 18")
print("Birthday: January 14, 2005")
print("Address: Zone 10B, Purok 6, Upper Carmen")
